### PR TITLE
Compatibility with GHC 9.8

### PR DESCRIPTION
**Pull request by rvl**
This patch lets blaze-svg compile with GHC 9.8 and bumps the version to 0.3.7.1.

However, it may be better to edit the package version bounds on Hackage.

### CODE REVIEW

**Comment by rvl** [comment]
Hi @byorgey, there are a few other packages which I know can build with GHC 9.8, if their `build-depends` version ranges are expanded accordingly. (Because of https://github.com/NixOS/nixpkgs/pull/276275)

| **Package** | **Offending bounds** | **Pull Request** |
| --- | --- | --- |
| [blaze-svg](https://hackage.haskell.org/package/blaze-svg) | `base <4.19` | https://github.com/diagrams/blaze-svg/pull/2 |
| [diagrams-lib](https://hackage.haskell.org/package/diagrams-lib) | `base <4.19, text <2.1` | https://github.com/diagrams/diagrams-lib/pull/364 |
| [diagrams-postscript](https://hackage.haskell.org/package/diagrams-postscript) | `base <4.19, bytestring <0.12` | |
| [diagrams-svg](https://hackage.haskell.org/package/diagrams-svg) | `base <4.19, text <2.1` | |
| [statestack](https://hackage.haskell.org/package/statestack) | `base <4.19` | https://github.com/diagrams/statestack/pull/11 |
| [svg-builder](https://hackage.haskell.org/package/svg-builder) | `base <4.19, bytestring <0.12, text <2.1` | |

Should I open similar PRs on those packages? Or are you happy to make revisions on Hackage?

**Comment by byorgey** [comment]
Hi @rvl , thanks!  I'm slowly working through updating all my packages, so no need to open more PRs, but I do appreciate the nudge.

**Comment by rvl** [comment]
Great, thanks. :+1:

**Comment by byorgey** [comment]
I went ahead and did this via my own typical workflow, and revised the bounds on Hackage.  I appreciate the PR though!

**Pull request closed without merging**
